import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SearchProvider } from "@/context/SearchContext";
import { Analytics } from "@vercel/analytics/next";
import { ThemeProvider } from "next-themes";
import ScrollToTop from "@/components/ScrollToTop";

export const metadata: Metadata = {
    title: "RhinoMovies",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <SearchProvider>
                        <Navbar />
                        {children}
                        <ScrollToTop />
                        <Footer />
                        <Analytics />
                    </SearchProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
