import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SearchProvider } from "@/context/SearchContext";

export const metadata: Metadata = {
    title: "RhinoMovies",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body>
                <SearchProvider>
                    <Navbar />
                    {children}
                    <Footer />
                </SearchProvider>
            </body>
        </html>
    );
}
